[project]
name = "robust-rail-generator"
version = "2.0.0-beta.1"
description = "Generator for scenarios of the Train Unit Shunting and Servicing (TUSS) Problem"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
