# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Location_HIP.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Location_HIP.proto',
  package='mypackage_hip',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12Location_HIP.proto\x12\rmypackage_hip\"\x91\x01\n\x08Location\x12,\n\ntrackParts\x18\x01 \x03(\x0b\x32\x18.mypackage_hip.TrackPart\x12+\n\nfacilities\x18\x02 \x03(\x0b\x32\x17.mypackage_hip.Facility\x12*\n\ttaskTypes\x18\x03 \x03(\x0b\x32\x17.mypackage_hip.TaskType\"Q\n\x08Resource\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\x0btrackPartId\x18\x03 \x01(\x04H\x00\x12\x14\n\nfacilityId\x18\x04 \x01(\x04H\x00\x42\n\n\x08resource\"\x8b\x01\n\x08\x46\x61\x63ility\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x19\n\x11relatedTrackParts\x18\x03 \x03(\x04\x12*\n\ttaskTypes\x18\x04 \x03(\x0b\x32\x17.mypackage_hip.TaskType\x12\x1e\n\x16simultaneousUsageCount\x18\x05 \x01(\r\"\xb3\x01\n\tTrackPart\x12\n\n\x02id\x18\x01 \x01(\x04\x12*\n\x04type\x18\x02 \x01(\x0e\x32\x1c.mypackage_hip.TrackPartType\x12\r\n\x05\x61Side\x18\x03 \x03(\x04\x12\r\n\x05\x62Side\x18\x04 \x03(\x04\x12\x0e\n\x06length\x18\x05 \x01(\x01\x12\x0c\n\x04name\x18\x06 \x01(\t\x12\x1a\n\x12sawMovementAllowed\x18\x07 \x01(\x08\x12\x16\n\x0eparkingAllowed\x18\x08 \x01(\x08\"`\n\x08TaskType\x12\x37\n\npredefined\x18\x01 \x01(\x0e\x32!.mypackage_hip.PredefinedTaskTypeH\x00\x12\x0f\n\x05other\x18\x02 \x01(\tH\x00\x42\n\n\x08taskType*q\n\rTrackPartType\x12\x0c\n\x08RailRoad\x10\x00\x12\n\n\x06Switch\x10\x01\x12\x11\n\rEnglishSwitch\x10\x02\x12\x15\n\x11HalfEnglishSwitch\x10\x03\x12\x10\n\x0cIntersection\x10\x04\x12\n\n\x06\x42umper\x10\x05*V\n\x12PredefinedTaskType\x12\x08\n\x04Move\x10\x00\x12\t\n\x05Split\x10\x01\x12\x0b\n\x07\x43ombine\x10\x02\x12\x08\n\x04Wait\x10\x03\x12\n\n\x06\x41rrive\x10\x04\x12\x08\n\x04\x45xit\x10\x05\x62\x06proto3'
)

_TRACKPARTTYPE = _descriptor.EnumDescriptor(
  name='TrackPartType',
  full_name='mypackage_hip.TrackPartType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RailRoad', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Switch', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EnglishSwitch', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HalfEnglishSwitch', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Intersection', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Bumper', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=690,
  serialized_end=803,
)
_sym_db.RegisterEnumDescriptor(_TRACKPARTTYPE)

TrackPartType = enum_type_wrapper.EnumTypeWrapper(_TRACKPARTTYPE)
_PREDEFINEDTASKTYPE = _descriptor.EnumDescriptor(
  name='PredefinedTaskType',
  full_name='mypackage_hip.PredefinedTaskType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Move', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Split', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Combine', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Wait', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Arrive', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Exit', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=805,
  serialized_end=891,
)
_sym_db.RegisterEnumDescriptor(_PREDEFINEDTASKTYPE)

PredefinedTaskType = enum_type_wrapper.EnumTypeWrapper(_PREDEFINEDTASKTYPE)
RailRoad = 0
Switch = 1
EnglishSwitch = 2
HalfEnglishSwitch = 3
Intersection = 4
Bumper = 5
Move = 0
Split = 1
Combine = 2
Wait = 3
Arrive = 4
Exit = 5



_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='mypackage_hip.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trackParts', full_name='mypackage_hip.Location.trackParts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='facilities', full_name='mypackage_hip.Location.facilities', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taskTypes', full_name='mypackage_hip.Location.taskTypes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=183,
)


_RESOURCE = _descriptor.Descriptor(
  name='Resource',
  full_name='mypackage_hip.Resource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mypackage_hip.Resource.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trackPartId', full_name='mypackage_hip.Resource.trackPartId', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='facilityId', full_name='mypackage_hip.Resource.facilityId', index=2,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='resource', full_name='mypackage_hip.Resource.resource',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=185,
  serialized_end=266,
)


_FACILITY = _descriptor.Descriptor(
  name='Facility',
  full_name='mypackage_hip.Facility',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mypackage_hip.Facility.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='mypackage_hip.Facility.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relatedTrackParts', full_name='mypackage_hip.Facility.relatedTrackParts', index=2,
      number=3, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='taskTypes', full_name='mypackage_hip.Facility.taskTypes', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='simultaneousUsageCount', full_name='mypackage_hip.Facility.simultaneousUsageCount', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=408,
)


_TRACKPART = _descriptor.Descriptor(
  name='TrackPart',
  full_name='mypackage_hip.TrackPart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mypackage_hip.TrackPart.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='mypackage_hip.TrackPart.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='aSide', full_name='mypackage_hip.TrackPart.aSide', index=2,
      number=3, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bSide', full_name='mypackage_hip.TrackPart.bSide', index=3,
      number=4, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='mypackage_hip.TrackPart.length', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='mypackage_hip.TrackPart.name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sawMovementAllowed', full_name='mypackage_hip.TrackPart.sawMovementAllowed', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parkingAllowed', full_name='mypackage_hip.TrackPart.parkingAllowed', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=411,
  serialized_end=590,
)


_TASKTYPE = _descriptor.Descriptor(
  name='TaskType',
  full_name='mypackage_hip.TaskType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='predefined', full_name='mypackage_hip.TaskType.predefined', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='other', full_name='mypackage_hip.TaskType.other', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='taskType', full_name='mypackage_hip.TaskType.taskType',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=592,
  serialized_end=688,
)

_LOCATION.fields_by_name['trackParts'].message_type = _TRACKPART
_LOCATION.fields_by_name['facilities'].message_type = _FACILITY
_LOCATION.fields_by_name['taskTypes'].message_type = _TASKTYPE
_RESOURCE.oneofs_by_name['resource'].fields.append(
  _RESOURCE.fields_by_name['trackPartId'])
_RESOURCE.fields_by_name['trackPartId'].containing_oneof = _RESOURCE.oneofs_by_name['resource']
_RESOURCE.oneofs_by_name['resource'].fields.append(
  _RESOURCE.fields_by_name['facilityId'])
_RESOURCE.fields_by_name['facilityId'].containing_oneof = _RESOURCE.oneofs_by_name['resource']
_FACILITY.fields_by_name['taskTypes'].message_type = _TASKTYPE
_TRACKPART.fields_by_name['type'].enum_type = _TRACKPARTTYPE
_TASKTYPE.fields_by_name['predefined'].enum_type = _PREDEFINEDTASKTYPE
_TASKTYPE.oneofs_by_name['taskType'].fields.append(
  _TASKTYPE.fields_by_name['predefined'])
_TASKTYPE.fields_by_name['predefined'].containing_oneof = _TASKTYPE.oneofs_by_name['taskType']
_TASKTYPE.oneofs_by_name['taskType'].fields.append(
  _TASKTYPE.fields_by_name['other'])
_TASKTYPE.fields_by_name['other'].containing_oneof = _TASKTYPE.oneofs_by_name['taskType']
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['Resource'] = _RESOURCE
DESCRIPTOR.message_types_by_name['Facility'] = _FACILITY
DESCRIPTOR.message_types_by_name['TrackPart'] = _TRACKPART
DESCRIPTOR.message_types_by_name['TaskType'] = _TASKTYPE
DESCRIPTOR.enum_types_by_name['TrackPartType'] = _TRACKPARTTYPE
DESCRIPTOR.enum_types_by_name['PredefinedTaskType'] = _PREDEFINEDTASKTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), {
  'DESCRIPTOR' : _LOCATION,
  '__module__' : 'Location_HIP_pb2'
  # @@protoc_insertion_point(class_scope:mypackage_hip.Location)
  })
_sym_db.RegisterMessage(Location)

Resource = _reflection.GeneratedProtocolMessageType('Resource', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCE,
  '__module__' : 'Location_HIP_pb2'
  # @@protoc_insertion_point(class_scope:mypackage_hip.Resource)
  })
_sym_db.RegisterMessage(Resource)

Facility = _reflection.GeneratedProtocolMessageType('Facility', (_message.Message,), {
  'DESCRIPTOR' : _FACILITY,
  '__module__' : 'Location_HIP_pb2'
  # @@protoc_insertion_point(class_scope:mypackage_hip.Facility)
  })
_sym_db.RegisterMessage(Facility)

TrackPart = _reflection.GeneratedProtocolMessageType('TrackPart', (_message.Message,), {
  'DESCRIPTOR' : _TRACKPART,
  '__module__' : 'Location_HIP_pb2'
  # @@protoc_insertion_point(class_scope:mypackage_hip.TrackPart)
  })
_sym_db.RegisterMessage(TrackPart)

TaskType = _reflection.GeneratedProtocolMessageType('TaskType', (_message.Message,), {
  'DESCRIPTOR' : _TASKTYPE,
  '__module__' : 'Location_HIP_pb2'
  # @@protoc_insertion_point(class_scope:mypackage_hip.TaskType)
  })
_sym_db.RegisterMessage(TaskType)


# @@protoc_insertion_point(module_scope)
