# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TrainUnitTypes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TrainUnitTypes.proto',
  package='mypackage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14TrainUnitTypes.proto\x12\tmypackage\"\xb4\x02\n\rTrainUnitType\x12\x13\n\x0b\x64isplayName\x18\x01 \x01(\t\x12\x11\n\tcarriages\x18\x02 \x01(\r\x12\x0e\n\x06length\x18\x04 \x01(\x01\x12\x17\n\x0f\x63ombineDuration\x18\x05 \x01(\x04\x12\x15\n\rsplitDuration\x18\x06 \x01(\x04\x12\x14\n\x0c\x62\x61\x63kNormTime\x18\x07 \x01(\x04\x12\x18\n\x10\x62\x61\x63kAdditionTime\x18\x08 \x01(\x04\x12\x13\n\x0btravelSpeed\x18\t \x01(\x04\x12\x13\n\x0bstartUpTime\x18\n \x01(\x04\x12\x12\n\ntypePrefix\x18\x0b \x01(\t\x12\x11\n\tneedsLoco\x18\x0c \x01(\x08\x12\x0e\n\x06isLoco\x18\r \x01(\x08\x12\x18\n\x10needsElectricity\x18\x0e \x01(\x08\x12\x10\n\x08idPrefix\x18\x0f \x01(\x05\"9\n\x0eTrainUnitTypes\x12\'\n\x05types\x18\x01 \x03(\x0b\x32\x18.mypackage.TrainUnitTypeb\x06proto3'
)




_TRAINUNITTYPE = _descriptor.Descriptor(
  name='TrainUnitType',
  full_name='mypackage.TrainUnitType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='displayName', full_name='mypackage.TrainUnitType.displayName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='carriages', full_name='mypackage.TrainUnitType.carriages', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='length', full_name='mypackage.TrainUnitType.length', index=2,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='combineDuration', full_name='mypackage.TrainUnitType.combineDuration', index=3,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='splitDuration', full_name='mypackage.TrainUnitType.splitDuration', index=4,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='backNormTime', full_name='mypackage.TrainUnitType.backNormTime', index=5,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='backAdditionTime', full_name='mypackage.TrainUnitType.backAdditionTime', index=6,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='travelSpeed', full_name='mypackage.TrainUnitType.travelSpeed', index=7,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startUpTime', full_name='mypackage.TrainUnitType.startUpTime', index=8,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='typePrefix', full_name='mypackage.TrainUnitType.typePrefix', index=9,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='needsLoco', full_name='mypackage.TrainUnitType.needsLoco', index=10,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isLoco', full_name='mypackage.TrainUnitType.isLoco', index=11,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='needsElectricity', full_name='mypackage.TrainUnitType.needsElectricity', index=12,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='idPrefix', full_name='mypackage.TrainUnitType.idPrefix', index=13,
      number=15, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=344,
)


_TRAINUNITTYPES = _descriptor.Descriptor(
  name='TrainUnitTypes',
  full_name='mypackage.TrainUnitTypes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='types', full_name='mypackage.TrainUnitTypes.types', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=403,
)

_TRAINUNITTYPES.fields_by_name['types'].message_type = _TRAINUNITTYPE
DESCRIPTOR.message_types_by_name['TrainUnitType'] = _TRAINUNITTYPE
DESCRIPTOR.message_types_by_name['TrainUnitTypes'] = _TRAINUNITTYPES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainUnitType = _reflection.GeneratedProtocolMessageType('TrainUnitType', (_message.Message,), {
  'DESCRIPTOR' : _TRAINUNITTYPE,
  '__module__' : 'TrainUnitTypes_pb2'
  # @@protoc_insertion_point(class_scope:mypackage.TrainUnitType)
  })
_sym_db.RegisterMessage(TrainUnitType)

TrainUnitTypes = _reflection.GeneratedProtocolMessageType('TrainUnitTypes', (_message.Message,), {
  'DESCRIPTOR' : _TRAINUNITTYPES,
  '__module__' : 'TrainUnitTypes_pb2'
  # @@protoc_insertion_point(class_scope:mypackage.TrainUnitTypes)
  })
_sym_db.RegisterMessage(TrainUnitTypes)


# @@protoc_insertion_point(module_scope)
